# Generated by Django 2.2.19 on 2021-02-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcardinformation",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
