# Generated by Django 2.2.19 on 2021-02-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_giftcardinformation_is_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcardinformation",
            name="redeemable_code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
