name: CI
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'
      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.1"
      - name: Install Dependencies
        run: uv sync --no-install-project
      - name: Format Check (Ruff)
        run: uv run ruff format --check --diff gcmanager/ tests/
      - name: Type Check (mypy)
        run: uv run mypy
      - name: Lint Check (Ruff)
        run: uv run ruff check gcmanager/ tests/
      - name: Common Security Checks (Ruff)
        run: uv run ruff check --select="S" gcmanager
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: '5.0.6'
          mongodb-username: testing_user
          mongodb-password: testing
          mongodb-port: 27020
      - name: Testing
        run: |
          uv run coverage erase
          uv run coverage run -mp unittest discover tests/unit --verbose
          uv run coverage run -mp unittest discover tests/integration --verbose
          uv run coverage combine
      - name: Coverage
        run: |
          uv run coverage report
          uv run coverage xml
      - name: Upload Coverage Report to CodeCov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
